monfree-exporter: add restart policy
So apparently we can fail to bind on `0.0.0.0`:

```
Traceback (most recent call last):
  File "/nix/store/7vly7mgs9bj3j2icishv06ba8pix6x8x-monfree-1.0.0/bin/.monfree-wrapped", line 9, in <module>
    sys.exit(main())
             ~~~~^^
  File "/nix/store/arz34j52pn122qjg7fdlj5g50dhmkklg-python3.14-click-8.2.1/lib/python3.14/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/nix/store/arz34j52pn122qjg7fdlj5g50dhmkklg-python3.14-click-8.2.1/lib/python3.14/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "/nix/store/arz34j52pn122qjg7fdlj5g50dhmkklg-python3.14-click-8.2.1/lib/python3.14/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/nix/store/arz34j52pn122qjg7fdlj5g50dhmkklg-python3.14-click-8.2.1/lib/python3.14/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/arz34j52pn122qjg7fdlj5g50dhmkklg-python3.14-click-8.2.1/lib/python3.14/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/arz34j52pn122qjg7fdlj5g50dhmkklg-python3.14-click-8.2.1/lib/python3.14/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/7vly7mgs9bj3j2icishv06ba8pix6x8x-monfree-1.0.0/lib/python3.14/site-packages/monfree/commands/exporter.py", line 124, in exporter
    wsgi_server, server_thread = prometheus_client.start_http_server(port, listen_addr)
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/nix/store/pidmcnklvk2f7v2aj45al3qadqk5asg6-python3.14-prometheus-client-0.22.1/lib/python3.14/site-packages/prometheus_client/exposition.py", line 234, in start_wsgi_server
    httpd = make_server(addr, port, app, TmpServer, handler_class=_SilentHandler)
  File "/nix/store/sddj4ifk8jdpqi1vzzz6cl7bb0cshskx-python3-3.14.0/lib/python3.14/wsgiref/simple_server.py", line 150, in make_server
    server = server_class((host, port), handler_class)
  File "/nix/store/sddj4ifk8jdpqi1vzzz6cl7bb0cshskx-python3-3.14.0/lib/python3.14/socketserver.py", line 457, in __init__
    self.server_bind()
    ~~~~~~~~~~~~~~~~^^
  File "/nix/store/sddj4ifk8jdpqi1vzzz6cl7bb0cshskx-python3-3.14.0/lib/python3.14/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/nix/store/sddj4ifk8jdpqi1vzzz6cl7bb0cshskx-python3-3.14.0/lib/python3.14/http/server.py", line 144, in server_bind
    socketserver.TCPServer.server_bind(self)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/nix/store/sddj4ifk8jdpqi1vzzz6cl7bb0cshskx-python3-3.14.0/lib/python3.14/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 99] Cannot assign requested address
```

I don't get it especially since we specify `after = [ "network.target" ];`…